version: '3'
services:
  db-cats-api:
    image: postgres:16
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: adminPosgress
      POSTGRES_USER: adminPosgress
      POSTGRES_DB: countryDb