spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/countryDb
    username: adminPosgress
    password: adminPosgress
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
spring-doc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
